[package]
name = "bevy_terrain"
description = "Terrain Rendering for the Bevy Engine."
version = "0.1.0-dev"
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["game-engines", "rendering", "graphics"]
keywords = ["gamedev", "graphics", "bevy", "3d", "terrain"]
exclude = ["assets/*"]
readme = "README.md"
authors = ["Kurt KÃ¼hnert <kurt@kuehnert.dev>"]
repository = "https://github.com/kurtkuehnert/bevy_terrain"

[dependencies]
bevy = "0.11"
dtm = "0.1"
rapid-qoi = "0.6"
ndarray = "0.15"
itertools = "0.10"
image = "0.24"
lru = "0.8"
bitflags = "1.3"
strum = "0.24"
strum_macros = "0.24"
fastrand = "1.7"
bytemuck = "1.10"
anyhow = "1.0"
bincode = "2.0.0-rc.1"
dolly = "0.4"



[[example]]
name = "basic"
path = "examples/basic.rs"
 
 [[example]]
name = "basic2"
path = "examples/basic2.rs"
 
 

[[example]]
name = "simpler"
path = "examples/simpler.rs"
 

[[example]]
name = "advanced"
path = "examples/advanced.rs"
 